FROM node:lts-slim AS cvat-ui

ENV TERM=xterm \
    LANG='C.UTF-8'  \
    LC_ALL='C.UTF-8'

# Install dependencies
RUN npm install -g corepack
COPY .yarnrc.yml /tmp/
COPY package.json /tmp/
COPY yarn.lock /tmp/
COPY cvat-core/package.json /tmp/cvat-core/
COPY cvat-canvas/package.json /tmp/cvat-canvas/
COPY cvat-canvas3d/package.json /tmp/cvat-canvas3d/
COPY cvat-ui/package.json /tmp/cvat-ui/
COPY cvat-data/package.json /tmp/cvat-data/

# Install common dependencies
WORKDIR /tmp/
RUN DISABLE_HUSKY=1 yarn install --immutable

# Build source code
COPY cvat-data/ /tmp/cvat-data/
COPY cvat-core/ /tmp/cvat-core/
COPY cvat-canvas3d/ /tmp/cvat-canvas3d/
COPY cvat-canvas/ /tmp/cvat-canvas/
COPY cvat-ui/ /tmp/cvat-ui/

ARG CLIENT_PLUGINS
ARG SOURCE_MAPS_ENABLED=false

RUN NODE_OPTIONS="--max-old-space-size=2048" \
CLIENT_PLUGINS="${CLIENT_PLUGINS}" \
SOURCE_MAPS_ENABLED="${SOURCE_MAPS_ENABLED}" yarn run build:cvat-ui

FROM nginxinc/nginx-unprivileged:1.29.5-alpine3.23-slim

# Replace default.conf configuration to remove unnecessary rules
# Files must be owned by nginx (101) since this image runs as non-root
COPY --chown=101:101 cvat-ui/react_nginx.conf /etc/nginx/conf.d/default.conf
COPY --chown=101:101 cvat-ui/robots.txt /usr/share/nginx/html/
COPY --chown=101:101 --from=cvat-ui /tmp/cvat-ui/dist /usr/share/nginx/html/
